//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int RoportID { get; set; }
        public Nullable<int> LearnerID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MarkLevelID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    
        public virtual Learner Learner { get; set; }
        public virtual MarkLevel MarkLevel { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
