//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int HomeworkID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Level { get; set; }
        public string Subject { get; set; }
        public string Questions { get; set; }
        public Nullable<float> MarkAchieved { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual HomeworkQuestion HomeworkQuestion { get; set; }
    }
}
