//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int HomeworkID { get; set; }
        public int LearnerID { get; set; }
        public System.DateTime HomeworkDate { get; set; }
        public string Description { get; set; }
    
        public virtual Learner Learner { get; set; }
    }
}
